/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Project metadata structure
 */
export interface ProjectMetadata {
  /**
   * Name of the group the project bolongs to
   */
  group: string;
  /**
   * Name of the project
   */
  name: string;
  /**
   * Description of the project
   */
  description: string;
  /**
   * URL of the project
   */
  projectUrl: string;
  /**
   * URL of the project repository
   */
  repositoryProjectUrl?: string;
  /**
   * URL of the project logo
   */
  logoUrl: string;
  /**
   * Addresses of the project contributors
   */
  contributors: string[];
  /**
   * Receiver of the hypercert
   */
  receiver: {
    receiverAddress: string;
    [k: string]: unknown;
  };
}
